import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';
import { LoginComponent } from './layouts/login-layout/login-layout.component';
import { RoleListComponent } from './components/role/role-list.component';
import { RoleCreateComponent } from './components/role/role-create.component';
import { RoleEditComponent } from './components/role/role-edit.component';
import { MainLayoutComponent } from './layouts/main-layout/main-layout.component';
import { UniteListComponent } from './components/unite/unite-list.component';
import { UniteCreateComponent } from './components/unite/unite-create.component';
import { UniteEditComponent } from './components/unite/unite-edit.component';
import { UnauthorizedComponent } from './components/unauthorized/unauthorized.component';
import { EmployeListComponent } from './components/employe/employe-list.component';
import { EmployeCreateComponent } from './components/employe/employe-create.component';
import { EmployeEditComponent } from './components/employe/employe-edit.component';
import { MaterielListComponent } from './components/materiel/materiel-list.component';
import { MaterielCreateComponent } from './components/materiel/materiel-create.component';
import { MaterielEditComponent } from './components/materiel/materiel-edit.component';
import { ServiceListComponent } from './components/service/service-list.component';
import { ServiceCreateComponent } from './components/service/service-create.component';
import { ServiceEditComponent } from './components/service/service-edit.component';
import { PosteListComponent } from './components/poste/poste-list.component';
import { PosteCreateComponent } from './components/poste/poste-create.component';
import { PosteEditComponent } from './components/poste/poste-edit.component';
import { FormulematerielListComponent } from './components/formulemateriel/formulemateriel-list.component';
import { FormulematerielCreateComponent } from './components/formulemateriel/formulemateriel-create.component';
import { FormulematerielEditComponent } from './components/formulemateriel/formulemateriel-edit.component';
import { FormuleroleListComponent } from './components/formulerole/formulerole-list.component';
import { FormuleroleCreateComponent } from './components/formulerole/formulerole-create.component';
import { FormuleroleEditComponent } from './components/formulerole/formulerole-edit.component';
import { ClientListComponent } from './components/client/client-list.component';
import { ClientCreateComponent } from './components/client/client-create.component';
import { ClientEditComponent } from './components/client/client-edit.component';
import { DemandeListComponent } from './components/demande/demande-list.component';
import { DemandeCreateComponent } from './components/demande/demande-create.component';
import { DemandeEditComponent } from './components/demande/demande-edit.component';
import { DevisListComponent } from './components/devis/devis-list.component';
import { DevisListClientComponent } from './components/devis/devis-list-client.component';
import { DevisCreateComponent } from './components/devis/devis-create.component';
import { DevisEditComponent } from './components/devis/devis-edit.component';
import { SignInLayoutComponent } from './layouts/sign-in-layout/sign-in-layout.component';
import { SignUpLayoutComponent } from './layouts/sign-up-layout/sign-up-layout.component';
import { DashboardComponent } from './components/dashboard/dashboard.component';
import { FactureListComponent } from './components/facture/facture-list.component';
import { FactureCreateComponent } from './components/facture/facture-create.component';
import { FactureEditComponent } from './components/facture/facture-edit.component';
import { DetaildevisListComponent } from './components/detaildevis/detaildevis-list.component';
import { DetaildevisCreateComponent } from './components/detaildevis/detaildevis-create.component';
import { DetaildevisEditComponent } from './components/detaildevis/detaildevis-edit.component';
import { TacheListComponent } from './components/tache/tache-list.component';
import { TacheCreateComponent } from './components/tache/tache-create.component';
import { TacheEditComponent } from './components/tache/tache-edit.component';
import { FactureListClientComponent } from './components/facture/facture-list-client.component';
import { StockListComponent } from './components/stock/stock-list.component';
import { StockCreateComponent } from './components/stock/stock-create.component';
import { StockEditComponent } from './components/stock/stock-edit.component';
//new_import
export const routes: Routes = [
  { path: '', redirectTo: 'sign-in', pathMatch: 'full' },
  { path: 'sign-in', component: SignInLayoutComponent },
  { path: 'sign-up', component: SignUpLayoutComponent },
  { path: 'login', component: LoginComponent },
  {
    path: '',
    component: MainLayoutComponent,
    // canActivate: [authGuard],
    children: [
      { path: 'unauthorized', component: UnauthorizedComponent },
      { path: 'roles-edit/:id', component: RoleEditComponent },
      { path: 'roles-create', component: RoleCreateComponent },
      { path: 'roles', component: RoleListComponent },
      { path: 'unites-edit/:id', component: UniteEditComponent },
      { path: 'unites-create', component: UniteCreateComponent },
      { path: 'unites', component: UniteListComponent },
      { path: 'employes-edit/:id', component: EmployeEditComponent },
      { path: 'employes-create', component: EmployeCreateComponent },
      { path: 'employes', component: EmployeListComponent },
      { path: 'materiels-edit/:id', component: MaterielEditComponent },
      { path: 'materiels-create', component: MaterielCreateComponent },
      { path: 'materiels', component: MaterielListComponent },
      { path: 'services-edit/:id', component: ServiceEditComponent },
      { path: 'services-create', component: ServiceCreateComponent },
      { path: 'services', component: ServiceListComponent },
      { path: 'postes-edit/:id', component: PosteEditComponent },
      { path: 'postes-create', component: PosteCreateComponent },
      { path: 'postes', component: PosteListComponent },
      { path: 'formulemateriels-edit/:id', component: FormulematerielEditComponent },
      { path: 'formulemateriels-create', component: FormulematerielCreateComponent },
      { path: 'formulemateriels', component: FormulematerielListComponent },
      { path: 'formuleroles-edit/:id', component: FormuleroleEditComponent },
      { path: 'formuleroles-create', component: FormuleroleCreateComponent },
      { path: 'formuleroles', component: FormuleroleListComponent },
      { path: 'clients-edit/:id', component: ClientEditComponent },
      { path: 'clients-create', component: ClientCreateComponent },
      { path: 'clients', component: ClientListComponent },
      { path: 'demandes-edit/:id', component: DemandeEditComponent },
      { path: 'demandes-create', component: DemandeCreateComponent },
      { path: 'demandes', component: DemandeListComponent },
      { path: 'devis-edit/:id', component: DevisEditComponent },
      { path: 'devis-create/:iddemande/:idclient', component: DevisCreateComponent },
      { path: 'devis', component: DevisListComponent },
      { path: 'devis-client', component: DevisListClientComponent },
      { path: 'dashboard', component: DashboardComponent },
      { path: 'factures-edit/:id', component: FactureEditComponent },
      { path: 'factures-create', component: FactureCreateComponent },
      { path: 'factures', component: FactureListComponent },
      { path: 'factures-client', component: FactureListClientComponent },
      { path: 'detaildevis-edit/:id', component: DetaildevisEditComponent },
      { path: 'detaildevis-create', component: DetaildevisCreateComponent },
      { path: 'detaildevis', component: DetaildevisListComponent },
      { path: 'taches-edit/:id', component: TacheEditComponent },
      { path: 'taches-create', component: TacheCreateComponent },
      { path: 'taches', component: TacheListComponent },
      { path: 'stocks-edit/:id', component: StockEditComponent },
      { path: 'stocks-create', component: StockCreateComponent },
      { path: 'stocks', component: StockListComponent },
      //new_path
    ]
  },
  { path: '**', redirectTo: 'login' }
];
